### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by fernandosmither** [Open-Source-eUdeC/UdeCursos-bot#5]
Holaa! qué hace este bot?

**Comment by CxrlosKenobi** [comment]
¡Hola @fernandosmither :wave: ! que gusto ver alguien de [osuc](https://github.com/open-source-uc) por aquí.
Básicamente el bot ayuda a mostrar cuántos días van faltando para las siguientes evaluaciones, las cuales los usuarios pueden modificar. De momento lo ocupamos las últimas 2 generaciónes de informática aquí en la UdeC, en nuestros respectivos grupos de generación en Telegram.

Para ver más info puedes revisar [aquí](https://github.com/Open-Source-eUdeC/UdeCursos-bot/blob/main/README.md).
